/* Autor: João Antonio Martins Filho*/
CREATE DATABASE CHATSOCKET;

USE CHATSOCKET;

CREATE TABLE User(
	ID Int Primary Key AUTO_INCREMENT,
    UserName VARCHAR(255) NOT NULL,
    UserLogin VARCHAR(255) NOT NULL,
    UserPassword VARCHAR(255) NOT NULL    
);

CREATE TABLE TypeWay (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE Message(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USERID INT NOT NULL,
    TYPEWAYID INT NOT NULL,
    DateMessage DATETIME NOT NULL,
    UserNameOrigin VARCHAR(255) NOT NULL,
    UserNameDestiny VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    
    CONSTRAINT USER_FK FOREIGN KEY (UserID) REFERENCES User(ID),
    CONSTRAINT TYPEWAY_FK FOREIGN KEY (TypeWayID) REFERENCES TypeWay(ID)
);